// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ``
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc69QE-2ffuOGoGt7M3wXfjHMDnLHG5O8',
    appId: '1:730298585272:web:807e821e57bbf80dbd244d',
    messagingSenderId: '730298585272',
    projectId: 'finalprj-92f33',
    authDomain: 'finalprj-92f33.firebaseapp.com',
    storageBucket: 'finalprj-92f33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfyP4_b2l3DHE43nJQqsTqFucAcyKzU_c',
    appId: '1:730298585272:android:2686b89a4f47f6e0bd244d',
    messagingSenderId: '730298585272',
    projectId: 'finalprj-92f33',
    storageBucket: 'finalprj-92f33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW4wz2R0v3-8I4WRREj-PtBBypiMrThfc',
    appId: '1:730298585272:ios:d431ad7f721ee32abd244d',
    messagingSenderId: '730298585272',
    projectId: 'finalprj-92f33',
    storageBucket: 'finalprj-92f33.firebasestorage.app',
    iosBundleId: 'com.example.ppeDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW4wz2R0v3-8I4WRREj-PtBBypiMrThfc',
    appId: '1:730298585272:ios:d431ad7f721ee32abd244d',
    messagingSenderId: '730298585272',
    projectId: 'finalprj-92f33',
    storageBucket: 'finalprj-92f33.firebasestorage.app',
    iosBundleId: 'com.example.ppeDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc69QE-2ffuOGoGt7M3wXfjHMDnLHG5O8',
    appId: '1:730298585272:web:79ac0f46652749a3bd244d',
    messagingSenderId: '730298585272',
    projectId: 'finalprj-92f33',
    authDomain: 'finalprj-92f33.firebaseapp.com',
    storageBucket: 'finalprj-92f33.firebasestorage.app',
  );
}
